version: '3.8'
services:
  db:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyclists
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data